-- START OF SQL/PL SCRIPT FOR PROJECT ZERO --- 

DROP TABLE ACTIVITY_TYPE; 
DROP TABLE ACTIVITY; 
DROP TABLE BANK_ACCOUNT; 
DROP TABLE ACCOUNT_TYPE; 
DROP TABLE USR; 
DROP TABLE USER_TYPE; 

CREATE TABLE USR (
USR_ID INTEGER PRIMARY KEY, 
FIRSTNAME VARCHAR2(100), 
LASTNAME VARCHAR2(100), 
USERNAME VARCHAR(100),  
PASSWORD VARCHAR(100), 
USR_TYPE_ID VARCHAR(100)
); 
/

ALTER TABLE USR
MODIFY ( 
    USERNAME VARCHAR2(100),  
    PASSWORD VARCHAR2(100), 
    USR_TYPE_ID VARCHAR2(100)
);
/ 

CREATE TABLE USR_TYPE ( 
USR_TYPE_ID VARCHAR2(100) PRIMARY KEY, 
USR_TYPE_NAME VARCHAR2(100)
); 
/

CREATE TABLE BANK_ACCOUNT ( 
BANK_ACCOUNT_ID INTEGER PRIMARY KEY, 
USR_ID INTEGER, 
ACCOUNT_TYPE_ID VARCHAR(100), 
BALANCE DOUBLE PRECISION 
); 
/

CREATE TABLE ACCOUNT_TYPE ( 
ACCOUNT_TYPE_ID VARCHAR2(100) PRIMARY KEY, 
ACCOUNT_TYPE_NAME VARCHAR2(100)
); 
/

CREATE TABLE ACTIVITY ( 
ACTIVITY_ID INTEGER PRIMARY KEY, 
BANK_ACCOUNT_ID INTEGER,
ACTIVITY_TYPE_ID INTEGER, 
TX_DATE DATE,
TX_DESCRIPTION VARCHAR2(100)
); 
/

ALTER TABLE ACTIVITY
MODIFY ( 
   ACTIVITY_TYPE_ID VARCHAR2(100)
);
/ 

CREATE TABLE ACTIVITY_TYPE(
ACTIVITY_TYPE_ID VARCHAR2(100) PRIMARY KEY, 
ACTIVITY_TYPE_NAME VARCHAR2(100)
); 
/

ALTER TABLE USR
ADD CONSTRAINT FK_USR_USR_TYPE
FOREIGN KEY(USR_TYPE_ID) REFERENCES USR_TYPE(USR_TYPE_ID); 

ALTER TABLE BANK_ACCOUNT
ADD CONSTRAINT FK_BANK_ACCOUNT_TYPE
FOREIGN KEY(ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE(ACCOUNT_TYPE_ID); 

ALTER TABLE BANK_ACCOUNT
ADD CONSTRAINT FK_BANK_ACCOUNT_USR
FOREIGN KEY(USR_ID) REFERENCES USR(USR_ID); 

ALTER TABLE ACTIVITY
ADD CONSTRAINT FK_ACTIVITY_BANK_ACCOUNT
FOREIGN KEY(BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT(BANK_ACCOUNT_ID);

ALTER TABLE ACTIVITY
ADD CONSTRAINT FK_ACTIVITY_ACTIVITY_TYPE
FOREIGN KEY(ACTIVITY_TYPE_ID) REFERENCES ACTIVITY_TYPE(ACTIVITY_TYPE_ID);

--- Put someone in some date for testing 
INSERT INTO USR_TYPE VALUES (1, 'standard'); 
INSERT INTO USR_TYPE VALUES (2, 'super');
INSERT INTO ACCOUNT_TYPE VALUES (1, 'checking'); 
INSERT INTO ACCOUNT_TYPE VALUES (2, 'savings');
INSERT INTO USR VALUES (1, 'Bob', 'Jones', 'BJones','p@ssword',1); 
INSERT INTO BANK_ACCOUNT VALUES (1, 1, 1, 10); 

CREATE OR REPLACE PROCEDURE USR_VIEW_ACCOUNT(UNAME IN VARCHAR2(100), PWORD IN VARCHAR2(100), S OUT SYS_REFCURSOR) IS
BEGIN 
    SELECT B.BANK_ACCOUNT_ID, B.USR_ID, B.ACCOUNT_TYPE_ID, B.BALANCE
    FROM BANK_ACCOUNT B
    INNER JOIN USR 
    ON 
        USR.USR_ID = B.USR_ID
    WHERE 
        (USR.USERNAME='BJones') AND (USR.PASSWORD='p@ssword'); 
END; 



/*
    SELECT B.BANK_ACCOUNT_ID, B.USR_ID, B.ACCOUNT_TYPE_ID, B.BALANCE
    FROM BANK_ACCOUNT B
    INNER JOIN USR 
    ON 
        USR.USR_ID = B.USR_ID
    WHERE 
        (USR.USERNAME='BJones') AND (USR.PASSWORD='p@ssword'); 
*/
        
      



